// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore;

#nullable disable

namespace RequirementTrackingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513074347_InitTable")]
    partial class InitTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("application_user", (string)null);
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.NotificationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RequirementId")
                        .HasColumnType("int")
                        .HasColumnName("requirement_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.ToTable("notification_job", (string)null);
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_attempt_at");

                    b.Property<int>("RequirementId")
                        .HasColumnType("int")
                        .HasColumnName("requirement_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<int>("RobotId")
                        .HasColumnType("int")
                        .HasColumnName("robot_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.HasIndex("RobotId");

                    b.ToTable("notification_log", (string)null);
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualLaunchDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actual_launch_date");

                    b.Property<DateTime?>("ActualTestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actual_test_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DocUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("doc_url");

                    b.Property<int>("FollowerId")
                        .HasColumnType("int")
                        .HasColumnName("follower_id");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PlanLaunchDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("plan_launch_date");

                    b.Property<DateTime?>("PlanStartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("plan_start_date");

                    b.Property<DateTime?>("PlanTestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("plan_test_date");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<int>("Progress")
                        .HasColumnType("int")
                        .HasColumnName("progress");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasColumnName("remark");

                    b.Property<string>("RequirementNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("requirement_no");

                    b.Property<int?>("RobotId")
                        .HasColumnType("int")
                        .HasColumnName("robot_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequirementNo")
                        .IsUnique();

                    b.HasIndex("RobotId");

                    b.ToTable("requirement", (string)null);
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id");

                    b.ToTable("robot", (string)null);
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("phone");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("real_name");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.NotificationJob", b =>
                {
                    b.HasOne("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Requirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.NotificationLog", b =>
                {
                    b.HasOne("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Requirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Robot", "Robot")
                        .WithMany()
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requirement");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Project", b =>
                {
                    b.HasOne("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Requirement", b =>
                {
                    b.HasOne("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequirementTrackingSystem.Infrastructure.DataPersistence.EfCore.Entities.Robot", "Robot")
                        .WithMany()
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Follower");

                    b.Navigation("Project");

                    b.Navigation("Robot");
                });
#pragma warning restore 612, 618
        }
    }
}
